#!/usr/bin/env bash
# Configures an Nginx server to listen to port 80

# Creates a symbolix link (-s) between the Nginx config file and the enable-sites directory
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restart Nginx
service nginx start

#terminates the first nginx process ID
kill "$(pgrep 'nginx' | head -1)"
